<?php
/**
 * @file
 */


/**
 * Implements hook_menu().
 */
function tours_menu() {
  $item['show_tours'] = array(
    'title' => 'Tours',
    'page callback' => 'tours_get_tours',
    'access callback' => TRUE,
  );
  $item['tours/autocomplete'] = array(
    'title' => 'Autocomplete',
    'page callback' => 'tours_autocomplete',
    'access callback' => TRUE,
  );
  $item['tours/autocomplete_to'] = array(
    'title' => 'Autocomplete',
    'page callback' => 'tours_autocomplete_to',
    'access callback' => TRUE,
  );
  $item['tours/search_tours'] = array(
    'title' => 'Search tour',
    'page callback' => 'tours_search_tours',
    'access callback' => TRUE,
  );
  return $item;
}

/**
 * Form builder for tour search form.
 */
function tours_tour_search_form($form, $form_state) {
  $form['city'] = array(
    '#type'	=> 'textfield',
    '#title' => t('City ​​of departure'),
    '#default_value' => $_GET['city'],
    '#attributes' => array(
    ),
    '#autocomplete_path' => 'tours/autocomplete',
  );

  $form['country_to'] = array(
    '#type'	=> 'textfield',
    '#title' => t('Country to'),
    '#default_value' => $_GET['country_to'],
    '#attributes' => array(
    ),
    '#autocomplete_path' => 'tours/autocomplete_to',
  );

  $form['date_of'] = array(
    '#type' => 'date_popup',
    '#title' => t('Date of'),
    '#date_format' => 'd.m.Y',
    '#default_value' => $_GET['date_of']['date'],
  );

  $form['date_to'] = array(
    '#type' => 'date_popup',
    '#title' => t('Date to'),
    '#date_format' => 'd.m.Y',
    '#default_value' => $_GET['date_of']['date'],
  );

  $form['search'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#attributes' => array(
    'class' => array(''),
    ),
  );

  $form['#method'] = 'GET';

  return $form;
}


/*
 * Submit for tours_tour_search_form.
 */
function tours_tour_search_form_submit(&$form, &$form_state) {
  $cities = tours_get_data_operator()->cities;
  $countries = tours_get_data_operator()->countries;
  foreach($cities as $value) {
    if($value->name == $form['city']['#value']) {
      $cityId = $value->cityId;
    }
  }
  foreach($countries as $value) {
    if($value->name == $form['country_to']['#value']) {
      $countryId = $value->countryId;
    }
  }
  $after = $form['date_of']['date']['#value'];
  $before = $form['date_to']['date']['#value'];

  $url = 'http://www.tez-tour.com/tariffsearch/getResult';
  $data = array(
    'priceMin' => '0',
    'priceMax' => '15000',
    'currency' => '5561',
    'nightsMin' => '6',
    'nightsMax' => '14',
    'hotelClassId' => '2567',
    'accommodationId' => '2',
    'rAndBId' => '15350',
    'tourType' => '1',
    'locale' => 'ru',
    'cityId' => $cityId,
    'countryId' => $countryId,
    'after' => $after,
    'before' => $before,
    //'hotelId' => '147264',
    'hotelInStop' => 'false',
    'specialInStop' => 'false',
    'version' => '2',
    'tourId' => '14259',
    'tourId' => '14259%2C14358',
    'tourId' => '14259%2C14358',
    'tourId' => '14369%2C14358',
    'tourId' => '14372%2C14358',
    'tourId' => '14369',
    'hotelClassBetter' => 'true',
    'rAndBBetter' => 'true',
    'noTicketsTo' => 'false',
    'noTicketsFrom' => 'false',
    'searchTypeId' => '3',
    'recommendedFlag' => 'false',
    'salePrivateFlag' => 'false',
    'onlineConfirmFlag' => 'false',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $tours = json_decode($result->data);
  var_dump($tours->date);
}

/*
 *  Get data from the operator
 */

function tours_get_data_operator() {
  $url = 'http://search.tez-tour.com/toursearch/references';
  $data = array(
    'locale' => 'ru',
    'formatResult' => 'true',
    'xml' => 'false',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $result = json_decode($result->data);

  return $result;
}

/**
 * Autocomplete callback.
 */
function tours_autocomplete($string) {
  $result = tours_get_data_operator();
  $data = $result->cities;
  $matches = array();
  if($string) {
    foreach($data as $key => $value){
      if(preg_match("/$string/i", $value->name)) {
        $matches[$value->name] = $value->name;
      }
    }
  }
  drupal_json_output($matches);
}

/**
 * Autocomplete_to callback.
 */
function tours_autocomplete_to($string) {
  $result = tours_get_data_operator();
  $data = $result->countries;
  $matches = array();
  if($string) {
    foreach($data as $key => $value){
      if(preg_match("/$string/i", $value->name)) {
        $matches[$value->name] = $value->name;
      }
    }
  }
  drupal_json_output($matches);
}

/*
 * Page callback tours/search_tours
 */

function tours_search_tours() {

}

/*
 * Page callback tours/show_tours.
 */
function tours_get_tours() {
  header ("Content-Type: text/html; charset=UTF-8");
  $url = 'http://www.tez-tour.com/tariffsearch/getResult';
  $data = array(
    'priceMin' => '0',
    'priceMax' => '15000',
    'currency' => '5561',
    'nightsMin' => '6',
    'nightsMax' => '14',
    'hotelClassId' => '2567',
    'accommodationId' => '2',
    'rAndBId' => '15350',
    'tourType' => '1',
    'locale' => 'ru',
    'cityId' => '2190',
    'countryId' => '12695',
    'after' => '10.10.2014',
    'before' => '31.10.2014',
    'hotelId' => '147264',
    'hotelInStop' => 'false',
    'specialInStop' => 'false',
    'version' => '2',
    'tourId' => '14259',
    'tourId' => '14259%2C14358',
    'tourId' => '14259%2C14358',
    'tourId' => '14369%2C14358',
    'tourId' => '14372%2C14358',
    'tourId' => '14369',
    'hotelClassBetter' => 'true',
    'rAndBBetter' => 'true',
    'noTicketsTo' => 'false',
    'noTicketsFrom' => 'false',
    'searchTypeId' => '3',
    'recommendedFlag' => 'false',
    'salePrivateFlag' => 'false',
    'onlineConfirmFlag' => 'false',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $tours = json_decode($result->data);
  var_dump($tours);
}
