<?php
/**
 * @file
 */


/**
 * Implements hook_menu().
 */
function tours_menu() {
  $item['show_tours'] = array(
    'title' => 'Tours',
    'page callback' => 'tours_get_tours',
    'access callback' => TRUE,
  );
  $item['search_tours'] = array(
    'title' => 'Search tour',
    'page callback' => 'tours_search_tours',
    'access callback' => TRUE,
  );
  $item['hotel/%'] = array(
    'title' => 'Hotel',
    'page callback' => 'tours_hotel_tours',
    'page arguments' => array(1),
    'access callback' => TRUE,
  );
  $item['get_region'] = array(
    'title' => 'region',
    'page callback' => 'tours_get_region',
    'access callback' => TRUE,
  );
  $item['get_hotel'] = array(
    'page callback' => 'tours_get_hotel',
    'access callback' => TRUE,
  );
  return $item;
}

/**
 * Implements hook_menu().
 */

function tours_theme() {

  $items['tours_search_form'] = array(
      'template' => 'tours_search_form',
      'render element' => 'form',
    );
  $items['tours_search_tours'] = array(
    'template' => 'tours-search-tours',
    'variables' => array(
      'variables' => NULL,
    ),
  );
  $items['tours_hotel_tours'] = array(
    'template' => 'tours-hotel-tours',
  );
  $items['date_of_form'] = array(
    'template' => 'date-of-form',
  );

  return $items;
}

/*
 * Checking for dynamic pricing
 */

function tours_checking_dynamic($countryId, $cityId) {
  $directory_url = 'http://search.tez-tour.com/toursearch/getCalcTypes';
  $data_directory = array(
    'xml' => 'false',
    'formatResult' => 'true'
  );
  $url = url($directory_url, array('query' => $data_directory));
  $directory_http = drupal_http_request($url);
  $directory = json_decode($directory_http->data)->calcByTariffs;
  foreach($directory as $value) {
    if($value->arrCountry == $countryId && $value->depCity == $cityId ) {
      return TRUE;
    }
  }
  return FALSE;
}

/*
 * page callback to /get_region.
 */
function tours_get_region() {
  if (tours_checking_dynamic($_POST['country_to'], $_POST['city']) == TRUE ) {
    $url = url('http://search.tez-tour.com/tariffsearch/byCountry');
  }
  else {
    $url = url('http://search.tez-tour.com/toursearch/byCountry');
  }
  $data = array(
    'countryId' => $_POST['country_to'],
    'locale' => 'ru',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $result = json_decode($result->data);
  foreach($result->tours as $value) {
    if($value->tourId[1]){
      print "<option value=". $value->tourId[0] .",". $value->tourId[1] .">". $value->name ."</option>";
    }
    else {
      print "<option value=". $value->tourId[0] .">". $value->name ."</option>";
    }
  }
  exit();
}

/*
 * page callback to /get_hotel.
 */
function tours_get_hotel() {
  if (tours_checking_dynamic($_POST['country_to'], $_POST['city']) == TRUE ) {
    $url = url('http://search.tez-tour.com/tariffsearch/byCountry');
  }
  else {
    $url = url('http://search.tez-tour.com/toursearch/byCountry');
  }
  $data = array(
    'countryId' => $_POST['country_to'],
    'locale' => 'ru',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $result = json_decode($result->data);
  foreach($result->hotels as $value) {
    //if($_POST['region'] == $value->tourId) {
      print "<option value=". $value->hotelId .">". $value->name ."</option>";
    //}
  }
  exit();
}

/**
 * Form builder for tour search form.
 */
function tours_tour_search_form($form, $form_state) {
  $form['city'] = array(
    '#type'	=> 'select',
    '#title' => t('City ​​of departure'),
    '#default_value' => $_GET['city'],
    '#attributes' => array(
      'class' => array('form-control', 'chosen'),
    ),
    '#options' => tours_get_city_country('cities'),
  );

  $form['country_to'] = array(
    '#type'	=> 'select',
    '#title' => t('Country to'),
    '#default_value' => $_GET['country_to'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
    '#options' => tours_get_city_country('countries'),
  );

  $form['tourId'] = array(
    '#type'	=> 'select',
    '#title' => t('Region'),
    '#default_value' => $_GET['tourId'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['hotelId'] = array(
    '#type'	=> 'select',
    '#title' => t('Hotel'),
    '#default_value' => $_GET['hotelId'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['date_of'] = array(
    '#type' => 'date_popup',
    '#title' => t('Date of'),
    '#date_format' => 'd.m.Y',
    '#default_value' => $_GET['date_of']['date'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['date_to'] = array(
    '#type' => 'date_popup',
    '#title' => t('Date to'),
    '#date_format' => 'd.m.Y',
    '#default_value' => $_GET['date_of']['date'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['adults'] = array(
    '#type' => 'hidden',
    '#title' => t('Adults'),
    '#value' => empty($_GET['adults']) ? $_GET['adults'] = 1 : $_GET['adults'],
    '#attributes' => array(
      'id' => array('tours-count-adults'),
    ),
  );

  $form['children'] = array(
    '#type' => 'hidden',
    '#title' => t('Children'),
    '#value' => empty($_GET['children']) ? $_GET['children'] = 0 : $_GET['children'],
    '#attributes' => array(
      'id' => array('tours-count-children'),
    ),
  );
  $form['birthday1'] = array(
    '#type' => 'textfield',
    '#maxlength' => '2',
    '#default_value' => $_GET['birthday1'],
    '#attributes' => array(
      'class' => array('form-control'),
      'id' => array('children-birthday1'),
    ),
  );
  $form['birthday2'] = array(
    '#type' => 'textfield',
    '#maxlength' => '2',
    '#default_value' => $_GET['birthday2'],
    '#attributes' => array(
      'class' => array('form-control'),
      'id' => array('children-birthday2'),
    ),
  );
  $form['nightsMin'] = array(
    '#type' => 'textfield',
    '#title' => t('nightsMin'),
    '#maxlength' => '2',
    '#default_value' => $_GET['nightsMin'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );
  $form['nightsMax'] = array(
    '#type' => 'textfield',
    '#title' => t('nightsMax'),
    '#maxlength' => '2',
    '#default_value' => $_GET['nightsMax'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['priceMin'] = array(
    '#type' => 'textfield',
    '#title' => t('priceMin'),
    '#maxlength' => '6',
    '#default_value' => $_GET['priceMin'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );
  $form['priceMax'] = array(
    '#type' => 'textfield',
    '#title' => t('priceMax'),
    '#maxlength' => '6',
    '#default_value' => $_GET['priceMax'],
    '#attributes' => array(
      'class' => array('form-control'),
    ),
  );

  $form['search'] = array(
    '#type' => 'submit',
    '#value' => t('Search'),
    '#attributes' => array(
      'class' => array('btn btn-default sub'),
    ),
  );

  $form['#method'][] = 'GET';
  $form['#theme'][] = 'tours_search_form';
  $form['#action'] = '/search_tours';
  return $form;
}

/*
 *  Get data from the operator
 */

function tours_get_data_operator() {
  $url = 'http://search.tez-tour.com/toursearch/references';
  $data = array(
    'locale' => 'ru',
    'formatResult' => 'true',
    'xml' => 'false',
  );
  $full_url = url($url, array('query' => $data));
  $result = drupal_http_request($full_url);
  $result = json_decode($result->data);

  return $result;
}

/**
 * Autocomplete callback.
 */
function tours_get_city_country($param) {
  $result = tours_get_data_operator()->$param;
  foreach($result as $key => $value) {
    if($param == 'cities') {
      $data[$value->cityId] = $value->name;
    }
    elseif($param == 'countries') {
      $data[$value->countryId] = $value->name;
    }
  }
  return $data;
}

/**
 * Autocomplete_to callback.
 */
function tours_autocomplete_to($string) {
  $result = tours_get_data_operator();
  $data = $result->countries;
  $matches = array();
  if($string) {
    foreach($data as $value){
      if(preg_match("/$string/i", $value->name)) {
        $matches[$value->name] = $value->name;
      }
    }
  }
  drupal_json_output($matches);
}

/*
 * Page callback /hotel
 */

function tours_hotel_tours($hotelId) {
  return theme('tours_hotel_tours', array('hotelId' => $hotelId));
}

/*
 * Page callback /search_tours
 */
function tours_search_tours() {
  return theme('tours_search_tours', array());
}

/*
 * Get tours.
 */
function tours_get_tours($hotelId = NULL) {

  if($_GET['city']) {
    $cityId = $_GET['city'];
    $countryId = $_GET['country_to'];;

    if (tours_checking_dynamic($countryId, $cityId) == TRUE ) {
      $accommodations = 'http://www.tez-tour.com/tariffsearch/accommodations';
    }
    else{
      $accommodations = 'http://www.tez-tour.com/toursearch/accommodations';
    }
    $accommodations_query = array(
      'cityId' => $cityId,
      'countryId' => $countryId,
    );
    $adults = $_GET['adults'];
    $children = $_GET['children'];
    $accommodations_url = url($accommodations, array('query' => $accommodations_query));
    $accommodations_data = json_decode(drupal_http_request($accommodations_url)->data)->accommodations;
    foreach($accommodations_data as $value) {
      if($value->adult == $adults && $value->children == $children) {
        $accommodationId = $value->accommodationId;
      }
    }
    $after = $_GET['date_of']['date'];
    $before = $_GET['date_to']['date'];
    if (tours_checking_dynamic($countryId, $cityId) == TRUE ) {
      $url = 'http://www.tez-tour.com/tariffsearch/getResult';
      $dynamics = 1;
    }
    else{
      $url = 'http://www.tez-tour.com/toursearch/getResult';
      $dynamics = NULL;
    }
    $data = array(
      'currency' => '5561',
      'nightsMin' => '6',
      'nightsMax' => '14',
      'hotelClassId' => '2567',
      'accommodationId' => $accommodationId,
      'rAndBId' => '15350',
      'tourType' => '1',
      'locale' => 'ru',
      'cityId' => $cityId,
      'countryId' => $countryId,
      'after' => $after,
      'before' => $before,
      'hotelInStop' => 'false',
      'specialInStop' => 'false',
      'version' => '2',
      'hotelClassBetter' => 'true',
      'rAndBBetter' => 'true',
      'hotelId' => $hotelId,
      'noTicketsTo' => 'false',
      'noTicketsFrom' => 'false',
      'searchTypeId' => '3',
      'recommendedFlag' => 'false',
      'salePrivateFlag' => 'false',
      'onlineConfirmFlag' => 'false',
    );
    isset($_GET['priceMin']) ? $data['priceMin'] = $_GET['priceMin'] : $data['priceMin'] = '0';
    isset($_GET['priceMax']) ? $data['priceMax'] = $_GET['priceMax'] : $data['priceMax'] = '150000';
    isset($_GET['nightsMin']) ? $data['nightsMin'] = $_GET['nightsMin'] : $data['nightsMin'] = '6';
    isset($_GET['nightsMax']) ? $data['nightsMax'] = $_GET['nightsMax'] : $data['nightsMax'] = '14';
    isset($_GET['tourId']) ? $data['tourId'] = $_GET['tourId'] : $_GET['tourId'] = NULL;

    if($children == 1) {
      $data['birthday1'] = date('d.m.').(date('Y') - $_GET['birthday1']);
    }
    elseif($children == 2) {
      $data['birthday1'] =  date('d.m.').(date('Y') - $_GET['birthday1']);
      $data['birthday2'] =  date('d.m.').(date('Y') - $_GET['birthday2']);
    }
    $full_url = url($url, array('query' => $data));
    $result = drupal_http_request($full_url);
    return array(
      'tours' => json_decode($result->data)->data,
      'dynamics' => $dynamics,
    );
  }
  return false;
}