<?php
/**
 * @file
 * Ctools content type new_message.
 */

/**
 * Implements hook_ctools_content_types().
 */
function tours_country_ctools_content_types() {
  return array(
    'single' => TRUE,
    'title' => t('Countries'),
    'all contexts' => TRUE,
    'category' => t('Tours'),
    'hook theme' => 'tours_country_content_type_theme',
  );
}

/**
 * Implements hook_content_type_render().
 */
function tours_country_content_type_render($subtype, $conf, $panel_args, $context) {
  $term = menu_get_object('taxonomy_term', 2);
  $block = new stdClass();

  $view = views_get_view('terms');
  $view->set_display('country');
  $view->preview = TRUE;
  $view->display_handler->options['filters']['field_destinations_target_id']['value']['value'] = $term->tid;
  $view->pre_execute(array());
  $block->content = $view->display_handler->preview();
  $view->post_execute();

  return $block;
}
